# Generated by Django 5.2.5 on 2026-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchVisionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touch',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Id client'),
        ),
    ]
