# Generated by Django 5.2.5 on 2026-09-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchVisionApp', '0002_touch_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='set_points',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Punti per set'),
        ),
        migrations.AddField(
            model_name='match',
            name='sets_to_win',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Set per vincere'),
        ),
        migrations.AddField(
            model_name='match',
            name='tiebreak_points',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Punti tie-break'),
        ),
    ]
