# Generated by Django 5.2.5 on 2026-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchVisionApp', '0003_match_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_state',
            field=models.JSONField(blank=True, null=True, verbose_name='Stato live'),
        ),
    ]
