# Generated by Django 5.2.5 on 2026-09-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchVisionApp', '0004_match_live_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numero')),
                ('serving', models.CharField(choices=[('home', 'Casa'), ('guests', 'Ospiti')], max_length=6, verbose_name='Battuta')),
                ('rotation', models.PositiveSmallIntegerField(verbose_name='Rotazione')),
                ('winner', models.CharField(choices=[('home', 'Casa'), ('guests', 'Ospiti')], max_length=6, verbose_name='Vincitore')),
                ('home_score', models.PositiveIntegerField(verbose_name='Punteggio casa dopo il punto')),
                ('guest_score', models.PositiveIntegerField(verbose_name='Punteggio ospiti dopo il punto')),
                ('cause', models.CharField(blank=True, default='', max_length=40, verbose_name='Causa')),
                ('client_id', models.CharField(max_length=64, unique=True, verbose_name='Id client')),
                ('p1_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MatchVisionApp.player', verbose_name='Giocatore in posizione 1')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rallies', to='MatchVisionApp.set')),
            ],
            options={
                'verbose_name': 'Rally',
                'verbose_name_plural': 'Rally',
                'ordering': ['set', 'number', 'id'],
            },
        ),
    ]
