# Generated by Django 5.2.5 on 2026-09-29 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchVisionApp', '0005_rally'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventi'},
        ),
        migrations.AddField(
            model_name='event',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Id client'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dettagli'),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Punteggio ospiti'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Punteggio casa'),
        ),
        migrations.AddField(
            model_name='event',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='MatchVisionApp.set'),
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.CharField(default='home', max_length=6, verbose_name='Squadra'),
        ),
    ]
