# Generated by Django 5.2.5 on 2026-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchVisionApp', '0008_auth_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Id client'),
        ),
        migrations.AddField(
            model_name='set',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Id client'),
        ),
    ]
