# Generated by Django 5.2.5 on 2026-10-01 10:10

from django.db import migrations, models


# Rallies saved before this field: the reason comes from the touch that ended them ("Attacco ++")
ERRORS = {'Battuta': 'serve_error', 'Ricezione': 'reception_error', 'Alzata': 'set_error',
          'Attacco': 'attack_error', 'Muro': 'block_error', 'Difesa': 'defense_error'}
WINNERS = {'Battuta ++': 'serve', 'Attacco ++': 'attack', 'Muro ++': 'block'}


def reason_from_cause(rally):
    cause = rally.cause or ''
    if cause in WINNERS:
        return WINNERS[cause]
    if cause.endswith(' — —') and cause[:-4] in ERRORS:
        return ERRORS[cause[:-4]]
    if cause.startswith('Cartellino rosso'):
        return 'penalty' if rally.winner == 'guests' else 'opp_penalty'
    return ''


def fill_reasons(apps, schema_editor):
    Rally = apps.get_model('MatchVisionApp', 'Rally')
    for rally in Rally.objects.filter(reason=''):
        reason = reason_from_cause(rally)
        if reason:
            rally.reason = reason
            rally.save(update_fields=['reason'])


class Migration(migrations.Migration):

    dependencies = [
        ('MatchVisionApp', '0009_client_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='rally',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Motivo'),
        ),
        migrations.RunPython(fill_reasons, migrations.RunPython.noop),
    ]
